#docker-compose up
version: "3.9"
services:
  postgres:
    container_name: localPostgresSQLDB
    image: postgres
    environment:
      POSTGRES_DB: "local_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    networks:
      java13-network:
        aliases:
          - java13db
networks:
  java13-network:
    name: 'our_java13_network'
