#docker-compose up
version: "3.9"
services:
  deploy:
    container_name: java13app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localPostgresSQLDB:5432/local_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      java13-network:
        aliases:
          - java13app
networks:
  java13-network:
    name: 'our_java13_network'